# Code Generated by ZenTest v. 4.8.0
#                 classname: asrt / meth =  ratio%
#         AWS::ServiceError:    0 /   16 =   0.00%
#                       AWS:    0 /    1 =   0.00%

require 'test/unit/testcase'
require 'test/unit' if $0 == __FILE__

$LOAD_PATH.unshift File.expand_path(File.join(File.dirname(__FILE__), '..', 'lib', 'OriginalAWS'))
require 'OriginalAWS/AWS'

class TestAws < Test::Unit::TestCase
  def setup
    @aws = Object.new
    @aws.extend(AWS)
  end

  def teardown
    @aws = nil
  end

  def test_adjust_time
    raise NotImplementedError, 'Need to write test_adjust_time'
  end

  def test_aws_access_key
    raise NotImplementedError, 'Need to write test_aws_access_key'
  end

  def test_aws_access_key_equals
    raise NotImplementedError, 'Need to write test_aws_access_key_equals'
  end

  def test_aws_secret_key
    raise NotImplementedError, 'Need to write test_aws_secret_key'
  end

  def test_aws_secret_key_equals
    raise NotImplementedError, 'Need to write test_aws_secret_key_equals'
  end

  def test_build_query_params
    raise NotImplementedError, 'Need to write test_build_query_params'
  end

  def test_calculateStringToSignV0
    raise NotImplementedError, 'Need to write test_calculateStringToSignV0'
  end

  def test_calculateStringToSignV1
    raise NotImplementedError, 'Need to write test_calculateStringToSignV1'
  end

  def test_calculateStringToSignV2
    raise NotImplementedError, 'Need to write test_calculateStringToSignV2'
  end

  def test_current_time
    raise NotImplementedError, 'Need to write test_current_time'
  end

  def test_debug
    raise NotImplementedError, 'Need to write test_debug'
  end

  def test_debug_equals
    raise NotImplementedError, 'Need to write test_debug_equals'
  end

  def test_debug_request
    raise NotImplementedError, 'Need to write test_debug_request'
  end

  def test_debug_response
    raise NotImplementedError, 'Need to write test_debug_response'
  end

  def test_do_query
    raise NotImplementedError, 'Need to write test_do_query'
  end

  def test_do_rest
    raise NotImplementedError, 'Need to write test_do_rest'
  end

  def test_encode_base64
    raise NotImplementedError, 'Need to write test_encode_base64'
  end

  def test_generate_rest_signature
    raise NotImplementedError, 'Need to write test_generate_rest_signature'
  end

  def test_generate_signature
    raise NotImplementedError, 'Need to write test_generate_signature'
  end

  def test_secure_http
    raise NotImplementedError, 'Need to write test_secure_http'
  end

  def test_secure_http_equals
    raise NotImplementedError, 'Need to write test_secure_http_equals'
  end

  def test_sign
    raise NotImplementedError, 'Need to write test_sign'
  end

  def test_signParameters
    raise NotImplementedError, 'Need to write test_signParameters'
  end

  def test_time_offset
    raise NotImplementedError, 'Need to write test_time_offset'
  end
end

# Number of errors detected: 30
