# Code Generated by ZenTest v. 4.8.0
#                 classname: asrt / meth =  ratio%
#         AWS::ServiceError:    0 /   16 =   0.00%
#                       AWS:    0 /    1 =   0.00%

require 'test/unit/testcase'
require 'test/unit' if $0 == __FILE__

$LOAD_PATH.unshift File.expand_path(File.join(File.dirname(__FILE__), '..', 'lib', 'OriginalAWS'))
require 'OriginalAWS/AWS'

class TestAws < Test::Unit::TestCase; end

class TestAws::TestServiceError < Test::Unit::TestCase
  def test_aws_error_xml
    raise NotImplementedError, 'Need to write test_aws_error_xml'
  end

  def test_aws_error_xml_equals
    raise NotImplementedError, 'Need to write test_aws_error_xml_equals'
  end

  def test_response
    raise NotImplementedError, 'Need to write test_response'
  end

  def test_response_equals
    raise NotImplementedError, 'Need to write test_response_equals'
  end
end
